name: Updating foundations file

on:
  schedule:
    - cron: '40 11 * * 2' # At 10:40 AM UTC every Tuesday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to GitHub runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Install the Python version needed

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute Python script
        run: python fetchingcomments_foundations.py
