name: Run fetchingcomments_foundations.py

on:
  schedule:
    - cron: '40 11 * * 2' # At 10:40 AM UTC every Tuesday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to GitHub runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Install the Python version needed

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute Python script
        run: python fetchingcomments_foundations.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -m "Automated commit" -a || echo "No changes to commit")
          
      - name: Fetch changes from main
        run: git fetch origin main

      - name: Merge changes from main
        run: git merge origin/main

      - name: Push changes
        run: git push origin main
